# name of this run of the pipeline
run_name: results

# name of the excel template file that contains molecule name/id, mz list, and rt list to collect
template_file: template.xlsx

# full path to the imput directory where your files to be processed live
input_dir: C:\Jack\code\GCMS_Automation\data

# path relative to input dir where results will be stored
results_dir: results/

# name of the file containing mzML files to process
mzml_dir: mzml_files/

rt_threshold: 0.1                   # max time (seconds) from the supplied rt a peak can be or peak is flagged
endpoint_threshold: 10              # max difference between endpoint heights (as a percent of max height of peak) for peak to be flagged
variance_threshold: 1e-6            # minimum variance to be included in PCA plot
pca_var: 0.8                        # decimal percent of how much variance accounted for by plotted pca, 0.8 means plot all pcs that in sum account for 80% of variance